---
# tasks file for post_check

- name: gather facts
  ios_facts:

- name: check image version
  debug:
    msg: "The current image verison is {{ ansible_net_version }}"

- name: set image_version_check to pass
  set_fact:
    image_version_check: "pass"
  when: "ansible_net_version == desired_image_version"

- name: fail task if image version check fails
  fail:
    msg: "Incorrect Version Detected After Upgrade. Please Check!"
  when: image_version_check != "pass"

- name: check back the state
  ios_command:
    commands: show ip int brief

- name: ping check to gateways
  ios_command:
    commands: ping "{{ item }}"
  with_items: "{{ gateways }}" 

- name: noti for slack
  slack:
      token:  "{{ slack_webhook }}"
      channel: "{{ slack_channel }}"
      msg: "ios version is {{ ansible_net_version }} now!"
  delegate_to: localhost
